# Run all the components of our project

# NOT ready to be used (in development nor production)
# Feel free to make this work then let us know to switch over to it
# @AdnanSlef will get to this later otherwise

services:
  anvil:
    build:
      context: ./smart-contract/deployment
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8545:8545"
    # environment:
      # - RPC_URL=http://localhost:8545

  frontend:
    build:
      context: ./frontend-uiux
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - prover
    volumes:
      - verifier_volume:/app/noir_circuits/target

  builder:
    build:
      context: ./smart-contract
      dockerfile: Dockerfile
    # Since we also deploy in builder, for now
    depends_on:
      - anvil
      - prover
    volumes:
      - verifier_volume:/app/noir_circuits/target

  prover:
    build:
      context: ./claim-prover
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8083:8080"
    volumes:
      - verifier_volume:/app/noir_circuits/target

  tee-host:
    build:
      context: ./rewards-calculator/tee
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - dstack-sockets:/app/src/dstack/sdk/simulator/

  tee-client:
    build:
      context: ./rewards-calculator/enclave_app
      target: dev
    environment:
      NODE_ENV: development
      # Custom campaigns! Pick whichever you like or add a new one!
      # CAMPAIGN: "/usr/src/app/CampaignTypes/PreknownCampaign.js"
      CAMPAIGN: "/usr/src/app/CampaignTypes/Web3CampaignForte.js"
      # CAMPAIGN: "/usr/src/app/CampaignTypes/Web3CampaignPYUSD.js"

    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - dstack-sockets:/var/run/

volumes:
  verifier_volume:
  dstack-sockets: